import {useEffect,useState} from "react";
import {ShieldCheck,RefreshCw} from "lucide-react";
import {Link} from "react-router-dom";
import {base44} from "@/api/base44Client";
import {readAll,validCoordinates} from "@/lib/local-discovery";
import LocalShell from "@/components/local/LocalShell";
export default function Admin(){
 const [data,setData]=useState({merchants:[],offers:[],requests:[]});const [loading,setLoading]=useState(true);const [tab,setTab]=useState("requests");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const [merchants,offers,requests]=await Promise.all([readAll(base44.entities.Commercant),readAll(base44.entities.Offre),readAll(base44.entities.DemandeCommercant)]);setData({merchants,offers,requests});}catch{setError("Les données d’administration n’ont pas pu se charger.");}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const act=async(fn,success)=>{setBusy(true);setError("");setMessage("");try{await fn();await load();setMessage(success);}catch(e){setError(e.response?.data?.error||"L’opération n’a pas abouti.");}finally{setBusy(false);}};
 const missing=data.merchants.filter(m=>!validCoordinates(m.latitude,m.longitude));
 return <LocalShell><div className="cp-container cp-workspace"><div className="cp-page-title"><span className="cp-eyebrow"><ShieldCheck size={16}/>ADMINISTRATION</span><h1>Un réseau local qui inspire confiance.</h1><p>Validez les demandes, gérez la visibilité des commerces et vérifiez la qualité du catalogue.</p></div>
 <div className="cp-stats">{[["Commerces",data.merchants.length],["Offres",data.offers.length],["Demandes en attente",data.requests.filter(r=>r.statut==="en_attente").length],["Adresses à compléter",missing.length]].map(([label,n])=><div className="cp-stat" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>
 <div className="cp-workspace-tabs">{[["requests","Demandes"],["merchants","Commerces"],["offers","Offres"],["quality","Qualité des données"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={"cp-button cp-button-light "+(tab===id?"selected":"")} aria-pressed={tab===id}>{label}</button>)}<button className="cp-button cp-button-light" onClick={load} disabled={loading}><RefreshCw size={16}/>Actualiser</button></div>
 {error&&<p className="cp-error" role="alert">{error}</p>}{message&&<p className="cp-success" role="status">{message}</p>}
 {loading?<div className="cp-empty" role="status">Chargement de l’administration…</div>:<section className="cp-panel">
 {tab==="requests"&&<><h2>Demandes de référencement</h2>{!data.requests.length?<p className="cp-muted">Aucune demande à afficher.</p>:<div className="cp-table-scroll"><table className="cp-table"><thead><tr><th>Commerce</th><th>Coordonnées</th><th>Statut</th><th>Décision</th></tr></thead><tbody>{data.requests.map(r=><tr key={r.id}><td><strong>{r.nom_commerce}</strong><br/>SIRET : {r.siret}<br/>{r.categorie}</td><td>{r.adresse}, {r.ville}<br/>{r.email_contact}</td><td>{r.statut==="approuve"?"Approuvée":r.statut==="refuse"?"Refusée":"En attente"}</td><td>{r.statut==="en_attente"&&<div className="cp-inline-actions" style={{margin:0}}><button disabled={busy} className="cp-button cp-button-primary" onClick={()=>act(()=>base44.functions.invoke("merchant-portal",{action:"approve",id:r.id}),"La demande a été validée et le commerce rattaché au compte.")}>Valider</button><button disabled={busy} className="cp-button cp-button-light" onClick={()=>act(()=>base44.functions.invoke("merchant-portal",{action:"reject",id:r.id}),"La demande a été refusée.")}>Refuser</button></div>}</td></tr>)}</tbody></table></div>}<p className="cp-muted" style={{marginTop:16}}>Vérifiez l’identité du demandeur et les informations du commerce avant d’approuver.</p></>}
 {tab==="merchants"&&<><h2>Commerces référencés</h2><div className="cp-table-scroll"><table className="cp-table"><thead><tr><th>Commerce</th><th>Adresse</th><th>Compte associé</th><th>Visibilité</th></tr></thead><tbody>{data.merchants.map(m=><tr key={m.id}><td><Link to={"/CommercantProfil?id="+encodeURIComponent(m.id)}><strong>{m.nom}</strong> ↗</Link><br/>{m.categorie}</td><td>{m.adresse}, {m.ville}<br/>{validCoordinates(m.latitude,m.longitude)?"Coordonnées renseignées":"Coordonnées manquantes"}</td><td>{m.user_id?"Oui":"À rattacher"}</td><td><button disabled={busy} className="cp-button cp-button-light" onClick={()=>act(()=>base44.entities.Commercant.update(m.id,{est_actif:!m.est_actif}),"La visibilité du commerce a été modifiée.")}>{m.est_actif?"Masquer":"Afficher"}</button></td></tr>)}</tbody></table></div></>}
 {tab==="offers"&&<><h2>Catalogue des offres</h2><p className="cp-muted">L’activation d’une offre reste soumise à ses dates et à son stock.</p><div className="cp-table-scroll"><table className="cp-table"><thead><tr><th>Offre</th><th>Commerce</th><th>Fin</th><th>État</th></tr></thead><tbody>{data.offers.map(o=><tr key={o.id}><td><Link to={"/OffreDetail?id="+encodeURIComponent(o.id)}>{o.titre} ↗</Link></td><td>{o.commercant_nom||"Non renseigné"}{!o.commercant_id&&<small><br/>Rattachement à vérifier</small>}</td><td>{o.date_fin?new Date(o.date_fin).toLocaleDateString("fr-FR"):"Non définie"}</td><td><button disabled={busy} className="cp-button cp-button-light" onClick={()=>act(()=>base44.entities.Offre.update(o.id,{est_active:!o.est_active}),"Le statut de l’offre a été modifié.")}>{o.est_active?"Désactiver":"Activer"}</button></td></tr>)}</tbody></table></div></>}
 {tab==="quality"&&<><h2>Une carte fiable commence par de bonnes fiches.</h2><p className="cp-muted" style={{margin:"12px 0"}}>{missing.length} commerce(s) sans coordonnées valides · {data.merchants.filter(m=>!m.image_url).length} sans photo principale · {data.merchants.filter(m=>!m.user_id).length} sans compte commerçant associé.</p><ul>{missing.map(m=><li key={m.id}>{m.nom} — {m.ville||"ville non renseignée"}</li>)}</ul><p className="cp-muted">Une coordonnée renseignée ne prouve pas à elle seule que l’adresse est correcte. Vérifiez les fiches avant de les présenter comme validées.</p><div className="cp-inline-actions"><Link to="/Dashboard" className="cp-button cp-button-primary">Gérer les offres d’un commerce</Link></div></>}
 </section>}</div></LocalShell>;
}