import {useState} from "react";
import {useQuery,useQueryClient} from "@tanstack/react-query";
import {ExternalLink,MapPin,ShieldCheck,Star} from "lucide-react";
import {base44} from "@/api/base44Client";
import {useAuth} from "@/lib/AuthContext";
import {directionsUrl,offerAvailable,safeHref} from "@/lib/local-discovery";
import LocalShell from "@/components/local/LocalShell";
import {CatalogueImage,OfferCard} from "@/components/local/CatalogueCards";

export default function CommercantProfil(){
  const id=new URLSearchParams(window.location.search).get("id"),{user}=useAuth(),cache=useQueryClient();
  const [note,setNote]=useState(0),[comment,setComment]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const query=useQuery({queryKey:["cp-merchant",id],enabled:Boolean(id),queryFn:async()=>{const [merchant,offers,reviews]=await Promise.all([base44.entities.Commercant.get(id),base44.entities.Offre.filter({commercant_id:id,est_active:true}),base44.entities.AvisCommercant.filter({commercant_id:id},"-date_avis",50)]);return {merchant,offers:offers.filter(offerAvailable),reviews};}});
  if(query.isPending)return <LocalShell><div className="cp-container cp-empty">Chargement du commerce…</div></LocalShell>;
  if(query.isError||!query.data?.merchant)return <LocalShell><div className="cp-container cp-empty"><h1>Commerce introuvable.</h1></div></LocalShell>;
  const {merchant,offers,reviews}=query.data,photo=safeHref(merchant.image_url),direction=directionsUrl(merchant);const average=reviews.length?(reviews.reduce((n,r)=>n+r.note,0)/reviews.length).toFixed(1):null;
  const submit=async e=>{e.preventDefault();if(!user){base44.auth.redirectToLogin(window.location.href);return;}setBusy(true);await base44.entities.AvisCommercant.create({user_id:user.id,commercant_id:id,note,commentaire:comment,date_avis:new Date().toISOString()});setNote(0);setComment("");setMessage("Merci, votre avis est publié.");await cache.invalidateQueries({queryKey:["cp-merchant",id]});setBusy(false);};
  return <LocalShell><section className="cp-container cp-merchant-page"><div className="cp-merchant-hero"><div className="cp-merchant-picture">{photo?<img src={photo} alt={merchant.nom}/>:<CatalogueImage item={merchant} title={merchant.nom}/>}</div><div><span className="cp-eyebrow">{merchant.est_verifie&&<><ShieldCheck size={15}/>COMMERCE VÉRIFIÉ</>}</span><h1>{merchant.nom}</h1><p>{merchant.categorie} · {merchant.ville}</p>{average&&<p className="cp-rating"><Star size={16} fill="currentColor"/> {average}/5 · {reviews.length} avis</p>}{direction&&<a className="cp-button cp-button-primary" href={direction} target="_blank" rel="noreferrer"><MapPin size={17}/>Itinéraire</a>}</div></div><div className="cp-detail-grid"><div>{merchant.description&&<section className="cp-panel"><h2>À propos</h2><p>{merchant.description}</p></section>}<section className="cp-panel"><h2>Informations pratiques</h2><p>{merchant.adresse}<br/>{merchant.ville}</p>{merchant.telephone&&<p><a href={"tel:"+merchant.telephone}>{merchant.telephone}</a></p>}{merchant.site_web&&<a className="cp-text-link" href={safeHref(merchant.site_web)} target="_blank" rel="noreferrer">Site officiel <ExternalLink size={13}/></a>}</section></div><aside className="cp-panel"><h2>Donner votre avis</h2><form onSubmit={submit}><div className="cp-stars">{[1,2,3,4,5].map(i=><button type="button" key={i} onClick={()=>setNote(i)} aria-label={i+" étoile"}><Star fill={i<=note?"currentColor":"none"}/></button>)}</div><label className="cp-field">Commentaire<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000}/></label><button className="cp-button cp-button-primary" disabled={!note||busy}>{busy?"Publication…":"Publier mon avis"}</button></form>{message&&<p className="cp-success">{message}</p>}</aside></div>{offers.length>0&&<section className="cp-detail-related"><h2>Offres en cours</h2><div className="cp-grid">{offers.map(o=><OfferCard item={o} key={o.id}/>)}</div></section>}</section></LocalShell>;
}