import {useState} from "react";
import {Send,CheckCircle2} from "lucide-react";
import {base44} from "@/api/base44Client";
import LocalShell from "@/components/local/LocalShell";

const initial={nom:"",email:"",sujet:"question",message:""};
export default function Contact(){
  const [form,setForm]=useState(initial),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState("");
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{await base44.entities.ContactMessage.create(form);setSent(true);setForm(initial);}catch{setError("Votre message n’a pas pu être enregistré. Connectez-vous puis réessayez.");}finally{setBusy(false);}};
  return <LocalShell><section className="cp-container cp-content-page"><div className="cp-page-title"><span className="cp-eyebrow">CONTACT</span><h1>Parlons de votre besoin.</h1><p>Une question sur une offre, un commerce ou le fonctionnement de Click & Promo ?</p></div>{sent?<div className="cp-empty"><CheckCircle2 size={40}/><h2>Message bien enregistré.</h2><p>Nous pourrons le traiter depuis l’espace d’administration.</p><button className="cp-button cp-button-light" onClick={()=>setSent(false)}>Envoyer un autre message</button></div>:<form className="cp-panel cp-contact-form" onSubmit={submit}>{error&&<p className="cp-error" role="alert">{error}</p>}<div className="cp-form-grid"><label className="cp-field">Nom<input value={form.nom} onChange={e=>set("nom",e.target.value)} required maxLength={120}/></label><label className="cp-field">Email<input type="email" value={form.email} onChange={e=>set("email",e.target.value)} required maxLength={200}/></label><label className="cp-field cp-field-full">Sujet<select value={form.sujet} onChange={e=>set("sujet",e.target.value)}><option value="question">Question générale</option><option value="commercant">Je suis commerçant</option><option value="probleme">Signaler un problème</option><option value="partenariat">Partenariat</option><option value="autre">Autre</option></select></label><label className="cp-field cp-field-full">Message<textarea value={form.message} onChange={e=>set("message",e.target.value)} required maxLength={5000}/></label></div><button className="cp-button cp-button-primary" disabled={busy}><Send size={17}/>{busy?"Enregistrement…":"Envoyer le message"}</button></form>}</section></LocalShell>;
}