import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Store,Plus,Save,ImagePlus,Trash2} from "lucide-react";
import {base44} from "@/api/base44Client";
import {CATEGORIES,searchPlaces} from "@/lib/local-discovery";
import LocalShell from "@/components/local/LocalShell";
const empty={titre:"",description:"",categorie:"Restaurant",type_reduction:"pourcentage",valeur_reduction:"",prix_original:"",prix_promo:"",date_debut:"",date_fin:"",stock_initial:"",stock_restant:"",conditions:"",code_promo:"",adresse:"",ville:"",latitude:"",longitude:"",est_active:false,est_urgente:false,image_urls:[],rayon_km:5};
const invoke=async action=>(await base44.functions.invoke("merchant-portal",action)).data;
const localDate=v=>{if(!v)return "";const d=new Date(v);if(!Number.isFinite(d.getTime()))return "";d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};
export default function Dashboard() {
  const [data,setData]=useState({merchants:[],offers:[]});const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");
  const [tab,setTab]=useState("offers");const [merchantId,setMerchantId]=useState("");const [form,setForm]=useState(empty);const [editing,setEditing]=useState(null);const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [places,setPlaces]=useState([]);const [remove,setRemove]=useState(null);
  const load=async()=>{setLoading(true);setError("");try{const result=await invoke({action:"context"});setData(result);setMerchantId(id=>id||result.merchants[0]?.id||"");}catch(e){setError(e.response?.data?.error||"L’espace commerçant n’a pas pu se charger.");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const merchant=data.merchants.find(m=>m.id===merchantId);const offers=data.offers.filter(o=>o.commercant_id===merchantId);
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  const create=()=>{setForm({...empty,categorie:merchant?.categorie||"Restaurant",adresse:merchant?.adresse||"",ville:merchant?.ville||"",latitude:merchant?.latitude??"",longitude:merchant?.longitude??""});setEditing(null);setError("");setSuccess("");setTab("edit");};
  const edit=o=>{setForm({...empty,...o,stock_initial:o.stock_initial??"",stock_restant:o.stock_restant??"",latitude:o.latitude??"",longitude:o.longitude??"",date_debut:localDate(o.date_debut),date_fin:localDate(o.date_fin),image_urls:o.image_urls?.length?o.image_urls:(o.image_url?[o.image_url]:[])});setEditing(o.id);setTab("edit");setError("");setSuccess("");};
  const save=async e=>{e.preventDefault();setBusy(true);setError("");setSuccess("");try{
    await invoke({action:"save",id:editing,merchant_id:merchantId,data:{...form,stock_restant:form.stock_restant===""?null:form.stock_restant,date_debut:form.date_debut?new Date(form.date_debut).toISOString():null,date_fin:form.date_fin?new Date(form.date_fin).toISOString():null}});
    await load();setTab("offers");setSuccess(form.est_active?"Votre offre a été enregistrée et activée.":"Votre brouillon a été enregistré.");setEditing(null);
  }catch(e){setError(e.response?.data?.error||"L’offre n’a pas été enregistrée.");}finally{setBusy(false);}};
  const upload=async e=>{const files=Array.from(e.target.files||[]);e.target.value="";setError("");if(form.image_urls.length+files.length>8){setError("Vous pouvez ajouter jusqu’à huit photos.");return;}if(files.some(f=>!["image/jpeg","image/png","image/webp"].includes(f.type)||f.size>5*1024*1024)){setError("Choisissez des images JPG, PNG ou WebP de 5 Mo maximum.");return;}setUploading(true);try{for(const file of files){const result=await base44.integrations.Core.UploadFile({file});setForm(f=>({...f,image_urls:[...f.image_urls,result.file_url]}));}}catch{setError("Une photo n’a pas pu être importée. Les photos déjà ajoutées sont conservées.");}finally{setUploading(false);}};
  const geocode=async()=>{setError("");setPlaces([]);try{const result=await searchPlaces([form.adresse,form.ville].filter(Boolean).join(", "));setPlaces(result);if(!result.length)setError("Adresse introuvable. Vérifiez la rue et la ville.");}catch(e){setError(e.message);}};
  const deleteOffer=async()=>{setBusy(true);setError("");try{await invoke({action:"delete",id:remove,merchant_id:merchantId});setRemove(null);await load();setSuccess("Offre supprimée.");}catch(e){setError(e.response?.data?.error||"La suppression a échoué.");}finally{setBusy(false);}};
  return <LocalShell><div className="cp-container cp-workspace"><div className="cp-page-title"><span className="cp-eyebrow"><Store size={15}/>ESPACE COMMERÇANT</span><h1>Votre commerce, en mouvement.</h1><p>Votre vitrine, vos offres et les chiffres enregistrés par l’application.</p></div>
    {error&&<div className="cp-error" role="alert">{error}{loading===false&&!data.merchants.length&&<button className="cp-button" onClick={load}>Réessayer</button>}</div>}{success&&<p className="cp-success" role="status">{success}</p>}
    {loading?<div className="cp-empty" role="status">Chargement de votre espace…</div>:data.merchants.length?<>
      <div className="cp-inline-actions" style={{marginBottom:24}}><label className="cp-field">Commerce<select value={merchantId} onChange={e=>{setMerchantId(e.target.value);setTab("offers");setEditing(null);}}>{data.merchants.map(m=><option key={m.id} value={m.id}>{m.nom}</option>)}</select></label><Link className="cp-button cp-button-light" to={"/CommercantProfil?id="+encodeURIComponent(merchantId)}>Voir ma fiche</Link><button className="cp-button cp-button-primary" onClick={create}><Plus size={17}/>Créer une offre</button></div>
      <div className="cp-stats">{[["Offres",offers.length],["Actives",offers.filter(o=>o.est_active).length],["Vues enregistrées",offers.reduce((n,o)=>n+(o.nb_vues||0),0)],["Utilisations enregistrées",offers.reduce((n,o)=>n+(o.nb_conversions||0),0)]].map(([label,value])=><div className="cp-stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
      {tab==="offers"?<section className="cp-panel"><h2>Mes offres</h2>{offers.length?<div className="cp-table-scroll"><table className="cp-table"><thead><tr><th>Offre</th><th>Statut</th><th>Fin</th><th>Actions</th></tr></thead><tbody>{offers.map(o=><tr key={o.id}><td><strong>{o.titre}</strong><br/>{o.categorie}</td><td>{!o.est_active?"Brouillon / inactive":o.date_fin&&Date.parse(o.date_fin)<=Date.now()?"Expirée":"Active"}</td><td>{o.date_fin?new Date(o.date_fin).toLocaleDateString("fr-FR"):"Non définie"}</td><td><div className="cp-inline-actions" style={{margin:0}}><button className="cp-button cp-button-light" onClick={()=>edit(o)}>Modifier</button><button className="cp-button cp-button-light" onClick={()=>setRemove(o.id)} aria-label={"Supprimer "+o.titre}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>:<div className="cp-empty"><h3>Votre première offre commence ici.</h3><p>Ajoutez des photos, les conditions et une date de fin.</p><button onClick={create} className="cp-button cp-button-primary">Créer une offre</button></div>}</section>:
      <form onSubmit={save} className="cp-panel"><h2 style={{marginBottom:24}}>{editing?"Modifier l’offre":"Une nouvelle raison de venir"}</h2><div className="cp-form-grid">
        <Field label="Titre de l’offre" value={form.titre} onChange={v=>set("titre",v)} required maxLength={160}/>
        <label className="cp-field">Catégorie<select value={form.categorie} onChange={e=>set("categorie",e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>
        <label className="cp-field cp-field-full">Description<textarea value={form.description} onChange={e=>set("description",e.target.value)} maxLength={5000} required/></label>
        <Field label="Prix initial (€)" type="number" min="0" step=".01" value={form.prix_original??""} onChange={v=>set("prix_original",v)}/><Field label="Prix promotionnel (€)" type="number" min="0" step=".01" value={form.prix_promo??""} onChange={v=>set("prix_promo",v)}/>
        <label className="cp-field">Type de réduction<select value={form.type_reduction} onChange={e=>set("type_reduction",e.target.value)}><option value="pourcentage">Pourcentage</option><option value="montant">Montant en euros</option></select></label><Field label="Valeur de la réduction" type="number" min="0" step=".01" max={form.type_reduction==="pourcentage"?100:undefined} value={form.valeur_reduction} onChange={v=>set("valeur_reduction",v)}/>
        <Field label="Début" type="datetime-local" value={form.date_debut} onChange={v=>set("date_debut",v)}/><Field label="Fin" type="datetime-local" value={form.date_fin} onChange={v=>set("date_fin",v)} required/>
        <Field label="Stock initial (facultatif)" type="number" min="0" step="1" value={form.stock_initial} onChange={v=>set("stock_initial",v)}/><Field label="Stock restant (facultatif)" type="number" min="0" step="1" value={form.stock_restant} onChange={v=>set("stock_restant",v)}/>
        <Field label="Adresse" value={form.adresse} onChange={v=>{setForm(f=>({...f,adresse:v,latitude:"",longitude:""}));}} required/><Field label="Ville" value={form.ville} onChange={v=>setForm(f=>({...f,ville:v,latitude:"",longitude:""}))} required/>
        <div className="cp-field-full"><button type="button" className="cp-button cp-button-light" onClick={geocode}>Vérifier l’adresse sur la carte</button>{places.map((p,i)=><button type="button" key={i} className="cp-button cp-button-light" style={{display:"flex",marginTop:8}} onClick={()=>{setForm(f=>({...f,latitude:p.lat,longitude:p.lon,ville:p.city||f.ville}));setPlaces([]);}}>{p.label}</button>)}<p className="cp-muted" style={{marginTop:8}}>{form.latitude!==""&&form.latitude!=null?"Coordonnées associées à l’offre.":"Vérifiez l’adresse pour positionner votre offre."}</p></div>
        <label className="cp-field cp-field-full">Conditions d’utilisation<textarea value={form.conditions} onChange={e=>set("conditions",e.target.value)} maxLength={3000}/></label><Field label="Code promotionnel (facultatif)" value={form.code_promo} onChange={v=>set("code_promo",v)} maxLength={100}/>
        <div className="cp-field-full"><label className="cp-field"><span><ImagePlus size={16} style={{verticalAlign:"middle"}}/> Photos de votre offre · {form.image_urls.length}/8</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading||form.image_urls.length>=8} onChange={upload}/></label><p className="cp-muted">JPG, PNG ou WebP · 5 Mo par photo. La première photo sert de couverture.</p><div className="cp-file-list" style={{marginTop:12}}>{form.image_urls.map((url,i)=><div className="cp-file-item" key={url+i}><img src={url} alt={"Photo "+(i+1)+" de l’offre"}/><button type="button" onClick={()=>set("image_urls",form.image_urls.filter((_,j)=>j!==i))}>Retirer la photo {i+1}</button></div>)}</div></div>
        <label className="cp-check"><input type="checkbox" checked={form.est_urgente} onChange={e=>set("est_urgente",e.target.checked)}/>Offre flash</label><label className="cp-check"><input type="checkbox" checked={form.est_active} onChange={e=>set("est_active",e.target.checked)}/>Activer l’offre</label>
      </div><div className="cp-inline-actions"><button className="cp-button cp-button-primary" disabled={busy||uploading}><Save size={17}/>{busy?"Enregistrement…":"Enregistrer"}</button><button type="button" onClick={()=>setTab("offers")} className="cp-button cp-button-light">Annuler</button></div></form>}
    </>:<div className="cp-empty"><h2>Aucun commerce disponible.</h2><p>Votre compte doit être associé à un commerce approuvé.</p><Link className="cp-button cp-button-primary" to="/InscriptionCommercant">Référencer mon commerce</Link></div>}
    {remove&&<section className="cp-notice" role="alert"><h3>Supprimer cette offre ?</h3><p>Cette action retire l’offre du catalogue.</p><div className="cp-inline-actions"><button className="cp-button cp-button-primary" disabled={busy} onClick={deleteOffer}>Confirmer la suppression</button><button className="cp-button cp-button-light" onClick={()=>setRemove(null)}>Annuler</button></div></section>}
  </div></LocalShell>;
}
function Field({label,value,onChange,...props}){return <label className="cp-field">{label}<input {...props} value={value} onChange={e=>onChange(e.target.value)}/></label>;}
