import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Store,Send,CheckCircle2} from "lucide-react";
import {base44} from "@/api/base44Client";
import {useAuth} from "@/lib/AuthContext";
import {CATEGORIES,searchPlaces} from "@/lib/local-discovery";
import LocalShell from "@/components/local/LocalShell";
const initial={nom_commerce:"",siret:"",categorie:"Restaurant",adresse:"",ville:"",code_postal:"",telephone:"",email_contact:"",description:"",site_web:"",latitude:null,longitude:null};
export default function InscriptionCommercant(){
 const {user}=useAuth();const [form,setForm]=useState(initial);const [existing,setExisting]=useState([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);const [places,setPlaces]=useState([]);const [geoBusy,setGeoBusy]=useState(false);
 useEffect(()=>{if(user)base44.entities.DemandeCommercant.filter({user_id:user.id}).then(setExisting).catch(()=>setError("Le suivi des demandes est indisponible. Réessayez dans un instant."));},[user?.id]);
 const set=(key,value)=>setForm(f=>({...f,[key]:value,...(["adresse","ville","code_postal"].includes(key)?{latitude:null,longitude:null}:{})}));
 const geocode=async()=>{setGeoBusy(true);setError("");try{const result=await searchPlaces([form.adresse,form.code_postal,form.ville].filter(Boolean).join(" "));setPlaces(result);if(!result.length)setError("Aucune adresse trouvée. Vérifiez les informations saisies.");}catch(e){setError(e.message);}finally{setGeoBusy(false);}};
 const submit=async e=>{e.preventDefault();setError("");const siret=form.siret.replace(/\s/g,"");if(!/^\d{14}$/.test(siret)){setError("Le SIRET doit comporter exactement 14 chiffres.");return;}if(form.latitude===null||form.longitude===null){setError("Vérifiez puis sélectionnez l’adresse du commerce avant d’envoyer.");return;}setBusy(true);try{await base44.entities.DemandeCommercant.create({...form,siret,user_id:user.id});setDone(true);}catch(e){setError(e.response?.data?.message||"Votre demande n’a pas été envoyée. Réessayez.");}finally{setBusy(false);}};
 return <LocalShell><div className="cp-container cp-workspace" style={{maxWidth:850}}><div className="cp-page-title"><span className="cp-eyebrow"><Store size={16}/>REJOINDRE CLICK & PROMO</span><h1>Faites découvrir votre commerce.</h1><p>Présentez votre activité. Après validation, votre compte ouvre l’accès à votre espace commerçant.</p></div>
 {done?<section className="cp-empty" role="status"><CheckCircle2 size={40}/><h2>Votre demande a bien été enregistrée.</h2><p>L’équipe peut maintenant vérifier votre commerce. Retrouvez l’avancement ici, avec ce même compte.</p><Link className="cp-button cp-button-primary" to="/">Découvrir les commerces</Link></section>:<>
 {existing.length>0&&<section className="cp-notice"><strong>Vos demandes</strong>{existing.map(r=><p key={r.id}>{r.nom_commerce} · {r.statut==="approuve"?"Approuvée":r.statut==="refuse"?"Refusée":"En cours de vérification"}</p>)}</section>}
 {error&&<p className="cp-error" role="alert">{error}</p>}
 <form className="cp-panel" onSubmit={submit}><div className="cp-form-grid">
 {[[ "nom_commerce","Nom du commerce","text"],["siret","SIRET (14 chiffres)","text"],["telephone","Téléphone professionnel","tel"],["email_contact","Email professionnel","email"]].map(([key,label,type])=><label className="cp-field" key={key}>{label}<input type={type} value={form[key]} onChange={e=>set(key,e.target.value)} required maxLength={key==="siret"?18:200}/></label>)}
 <label className="cp-field cp-field-full">Catégorie<select value={form.categorie} onChange={e=>set("categorie",e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label>
 <label className="cp-field cp-field-full">Adresse du commerce<input value={form.adresse} onChange={e=>set("adresse",e.target.value)} required autoComplete="street-address"/></label>
 <label className="cp-field">Ville<input value={form.ville} onChange={e=>set("ville",e.target.value)} required autoComplete="address-level2"/></label><label className="cp-field">Code postal<input value={form.code_postal} onChange={e=>set("code_postal",e.target.value)} required pattern="[0-9]{5}" inputMode="numeric" autoComplete="postal-code"/></label>
 <div className="cp-field-full"><button type="button" disabled={geoBusy||!form.adresse||!form.ville} onClick={geocode} className="cp-button cp-button-light">{geoBusy?"Recherche…":"Vérifier l’adresse"}</button>{places.map((p,i)=><button type="button" className="cp-button cp-button-light" key={i} style={{display:"flex",marginTop:8}} onClick={()=>{setForm(f=>({...f,latitude:p.lat,longitude:p.lon,ville:p.city||f.ville,code_postal:p.postcode||f.code_postal}));setPlaces([]);}}>{p.label}</button>)}{form.latitude!==null&&<p className="cp-success" role="status">Adresse sélectionnée. Votre commerce pourra être positionné sur la carte.</p>}</div>
 <label className="cp-field cp-field-full">Présentez votre activité<textarea value={form.description} onChange={e=>set("description",e.target.value)} required maxLength={3000}/></label><label className="cp-field cp-field-full">Site web (facultatif)<input type="url" value={form.site_web} onChange={e=>set("site_web",e.target.value)} placeholder="https://"/></label>
 </div><div className="cp-inline-actions"><button className="cp-button cp-button-primary" disabled={busy}><Send size={17}/>{busy?"Envoi…":"Envoyer ma demande"}</button><Link to="/" className="cp-button cp-button-light">Retour</Link></div></form></>}
 </div></LocalShell>;
}