import {useEffect,useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import {Bell,Clock3,Copy,LogOut,MapPin,Target,UserRound} from "lucide-react";
import {base44} from "@/api/base44Client";
import {useAuth} from "@/lib/AuthContext";
import LocalShell from "@/components/local/LocalShell";
import AlertPreferences from "@/components/local/AlertPreferences";

const makeCode=email=>"CP"+(email||"USER").replace(/[^A-Z0-9]/gi,"").toUpperCase().slice(0,4)+Math.floor(1000+Math.random()*9000);
export default function Profil(){
  const {user}=useAuth(),navigate=useNavigate(),[profile,setProfile]=useState(null),[history,setHistory]=useState([]),[tab,setTab]=useState("overview"),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
  useEffect(()=>{if(!user)return;(async()=>{let [p]=await base44.entities.ProfilUtilisateur.filter({user_id:user.id});if(!p)p=await base44.entities.ProfilUtilisateur.create({user_id:user.id,prenom:user.full_name?.split(" ")[0]||"",nom:user.full_name?.split(" ").slice(1).join(" ")||"",code_parrainage:makeCode(user.email)});const h=await base44.entities.HistoriqueOffresVues.filter({user_id:user.id},"-date_vue",30);setProfile(p);setHistory(h);setLoading(false);})();},[user?.id]);
  const toggleNotifications=async()=>{const value=profile.notifications_actives===false;const updated=await base44.entities.ProfilUtilisateur.update(profile.id,{notifications_actives:value});setProfile(updated);setMessage(value?"Notifications activées.":"Notifications désactivées.");};
  const copyCode=async()=>{await navigator.clipboard.writeText(profile.code_parrainage);setMessage("Code copié.");};
  if(loading)return <LocalShell><div className="cp-container cp-empty">Chargement de votre profil…</div></LocalShell>;
  return <LocalShell><section className="cp-container cp-workspace"><div className="cp-profile-head"><div className="cp-profile-avatar"><UserRound size={32}/></div><div><span className="cp-eyebrow">MON COMPTE</span><h1>{user.full_name||user.email}</h1><p>{user.email}</p></div></div><div className="cp-workspace-tabs">{[["overview","Aperçu"],["history","Historique"],["settings","Préférences"]].map(([id,label])=><button className={"cp-button cp-button-light "+(tab===id?"selected":"")} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>{message&&<p className="cp-success" role="status">{message}</p>}
    {tab==="overview"&&<><div className="cp-stats">{[[profile.total_economies||0,"€ économisés"],[profile.nb_offres_utilisees||0,"Offres utilisées"],[profile.points||0,"Points"],[profile.nb_filleuls||0,"Filleuls"]].map(([value,label])=><div className="cp-stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><section className="cp-panel"><h2><Target size={19}/> Votre code de parrainage</h2><p className="cp-muted">Partagez ce code avec vos proches.</p><div className="cp-code-row"><strong>{profile.code_parrainage}</strong><button className="cp-button cp-button-light" onClick={copyCode}><Copy size={16}/>Copier</button></div><Link className="cp-button cp-button-primary" to="/Feed">Découvrir les offres</Link></section></>}
    {tab==="history"&&<section className="cp-panel"><h2><Clock3 size={19}/> Offres récemment consultées</h2>{history.length?<div className="cp-history-list">{history.map(h=><Link to={"/OffreDetail?id="+h.offre_id} key={h.id}><div><strong>{h.offre_titre}</strong><span>{h.commercant_nom} · {h.ville}</span></div><small>{new Date(h.date_vue).toLocaleDateString("fr-FR")}</small></Link>)}</div>:<div className="cp-empty">Aucune offre consultée pour le moment.</div>}</section>}
    {tab==="settings"&&<section className="cp-panel cp-settings-list"><AlertPreferences profile={profile} onSaved={updated=>{setProfile(updated);setMessage("Préférences mobiles enregistrées pour plus tard.");}}/><button onClick={toggleNotifications}><Bell size={19}/><span>{profile.notifications_actives===false?"Activer":"Désactiver"} les notifications</span></button><button onClick={()=>navigate("/Carte")}><MapPin size={19}/><span>Gérer ma localisation sur la carte</span></button><button onClick={()=>base44.auth.logout("/")}><LogOut size={19}/><span>Se déconnecter</span></button></section>}
  </section></LocalShell>;
}